"""
Django settings for admin project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_-3jlpfh88c6k!$^ff==l6yeov*sq+-o)f0l8g-a!_6i&=3in8"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 

ALLOWED_HOSTS = [ "localhost", "administrative-prototype-for-tec-production.up.railway.app"]

X_FRAME_OPTIONS = "ALLOW-FROM http://localhost:8000"

CSRF_TRUSTED_ORIGINS = [
   "https://*.railway.app"
]

# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "servicos",
    "financas",
    "clientes",
    "import_export",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "admin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "admin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    #"default": {"ENGINE": "django.db.backends.sqlite3","NAME": BASE_DIR / "db.sqlite3",}
    #"default": {   "ENGINE": "django.db.backends.postgresql","NAME": "railway","USER": "postgres", "PASSWORD": "eiqYfBxdZVAlBFQmeFiPuqFfPoXDoCzj","HOST": "junction.proxy.rlwy.net","PORT": "38479",}
}

DATABASE_URL = "postgresql://postgres:eiqYfBxdZVAlBFQmeFiPuqFfPoXDoCzj@junction.proxy.rlwy.net:38479/railway"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/


LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login Configs

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/admin"

# Jazzmin Config

JAZZMIN_SETTINGS = {
    # Título da janela (Usará current_admin_site.site_title se ausente ou None)
    "site_title": "Technos",
    # Título na tela de login (máx. 19 caracteres) (padrão para current_admin_site.site_header se ausente ou None)
    "site_header": "Technos Jr.",
    # Título na marca (máx. 19 caracteres) (padrão para current_admin_site.site_header se ausente ou None)
    "site_brand": "Technos",
    # Logotipo para usar no seu site, deve estar presente nos arquivos estáticos, usado para a marca no canto superior esquerdo
    "site_logo": "img/logo.png",
    # Logotipo para usar no formulário de login (padrão para site_logo)
    "login_logo": "img/logo_login.png",  # Defina um logotipo diferente para o login, se necessário
    # Logotipo para usar no formulário de login em temas escuros (padrão para login_logo)
    "login_logo_dark": "img/logo_login.png",  # Adicione um logotipo escuro se necessário
    # Classes CSS aplicadas ao logotipo acima
    "site_logo_classes": "img-circle",
    # Caminho relativo para um favicon para o seu site, será padrão para site_logo se ausente (idealmente 32x32 px)
    "site_icon": "img/logo.png",  # Adicione um favicon personalizado
    # Texto de boas-vindas na tela de login
    "welcome_sign": "Bem-vindo à Administração",
    # Direitos autorais no rodapé
    "copyright": "Thera Ltd.",
    # Lista de modelos de administradores a serem buscados na barra de pesquisa, a barra de pesquisa é omitida se excluída
    # Se você quiser usar um único campo de pesquisa, não precisa usar uma lista, pode usar uma string simples
    "search_model": [
        # "auth.User",
        # "auth.Group",
        # "books.Book",
    ],  # Adicione modelos relevantes aqui
    # Nome do campo no modelo de usuário que contém ImageField/URLField/Charfield de avatar ou uma função que recebe o usuário
    "user_avatar": "profile.avatar",  # Se houver um campo de avatar no modelo de usuário
    ############
    # Menu Superior #
    ############
    # Links para colocar ao longo do menu superior
    "topmenu_links": [
        # URL que é revertida (Permissões podem ser adicionadas)
        # URL externa que abre em uma nova janela (Permissões podem ser adicionadas)
        {
            "name": "Suporte",
            "url": "https://github.com/theralab",
            "new_window": True,
        },
        # modelo admin para vincular (Permissões verificadas contra o modelo)
        {"model": "auth.User"},
        # App com menu suspenso para todas as páginas de seus modelos (Permissões verificadas contra modelos)
        {"app": "clientes"},
        {"app": "servicos"},
        {"app": "financas"},
        {"app": "estoque"},
    ],
    #############
    # Menu do Usuário #
    #############
    # Links adicionais para incluir no menu do usuário no canto superior direito ("app" tipo url não é permitido)
    "usermenu_links": [
        {
            "name": "Suporte",
            "url": "https://github.com/theralab/administrative-prototype-for-technos/issues",
            "new_window": True,
        },
        {"model": "auth.user"},
    ],
    #############
    # Menu Lateral #
    #############
    # Se deve exibir o menu lateral
    "show_sidebar": True,
    # Se o menu deve ser expandido automaticamente
    "navigation_expanded": True,
    # Ocultar esses apps ao gerar o menu lateral, e.g. (auth)
    "hide_apps": [],
    # Ocultar esses modelos ao gerar o menu lateral (e.g. auth.user)
    "hide_models": [],
    # Lista de apps (e/ou modelos) para basear a ordem do menu lateral (não precisa conter todos os apps/modelos)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    # Links personalizados para adicionar aos grupos de aplicativos, indexados pelo nome do aplicativo
    "custom_links": {
        "books": [
            {
                "name": "Criar Mensagens",
                "url": "make_messages",
                "icon": "fas fa-comments",
                "permissions": ["books.view_book"],
            }
        ],
        "admin": [
            {
                "name": "Dashboard",
                "url": "custom-dashboard",  # A URL que criamos
                "icon": "fas fa-chart-bar",
                "permissions": ["auth.view_user"],  # Ajuste conforme suas permissões
            },
        ],
    },
    # Ícones personalizados para apps/modelos do menu lateral
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "clientes.cliente": "fa-regular fa-address-card",
        "financas.caixa": "fa-solid fa-coins",
        "financas.entrada": "fa-solid fa-arrow-trend-up",
        "financas.saida": "fa-solid fa-arrow-trend-down",
        "servicos.pedido": "fa-solid fa-table",
        "servicos.consultoria": "fa-solid fa-handshake-angle",
        "servicos.manutencao": "fa-solid fa-screwdriver-wrench",
        "servicos.software": "fa-solid fa-computer",
        "servicos.gerais": "fa-solid fa-table-list",
    },
    # Ícones que são usados quando um não é especificado manualmente
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    #################
    # Modal Relacionado #
    #################
    # Usar modais em vez de pop-ups
    "related_modal_active": True,  # Ative modais para uma melhor experiência
    #############
    # Ajustes de UI #
    #############
    # Caminhos relativos para CSS/JS personalizados (devem estar presentes nos arquivos estáticos)
    #"custom_css": "admin/css/custom.css",  # Adicione um CSS personalizado
    #"custom_js": "admin/js/custom.js",  # Adicione um JS personalizado
    # Se deve vincular fonte de fonts.googleapis.com (use custom_css para fornecer fonte, caso contrário)
    "use_google_fonts_cdn": True,
    # Se deve mostrar o personalizador de UI na barra lateral
    #"show_ui_builder": True,  # Permita que os administradores ajustem a interface
    ###############
    # Visualização de Alterações #
    ###############
    # Renderizar a visualização de alterações como um único formulário ou em abas, opções atuais são
    # - single
    # - horizontal_tabs (padrão)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # substitua formulários de alteração em uma base por modeloadmin
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    # Adicione um dropdown de idiomas no admin
    # "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
